image: Visual Studio 2022
environment:
  secret:
    secure: DJozVgpz51jHWTRg0o0Ial/k/piev5RV973z7Jl6Yyh8JemzVPoDUL8DUiVNtp/U
  salt:
    secure: 7hZu0YMbZBd+uTd8KItAK/VHWNR7ZLOZaBEYpcK4bJNVNTKc0SO6B4id8F9DtKsQn95nE6wLUIyveAizwsMKBA==
init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
      else
      {
        Update-AppveyorBuild -Version "SNAPSHOT-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }
install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt Twimager\Resources\TwitterKeys.cs.enc -secret %secret% -salt %salt%
  - nuget restore
platform: Any CPU
configuration: Release
build:
  parallel: true
  project: Twimager.sln
artifacts:
  - path: Twimager\bin\$(configuration)
